/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author IsseI
 */
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import net.proteanit.sql.DbUtils;

import java.util.logging.Level;
import java.util.logging.Logger;

public class main_win extends javax.swing.JFrame {

    /**
     * Creates new form main_win
     */
        Connection com;
    Statement st;
    ResultSet rs;
   LOGIN s;
   String k;
   String ts;
       public void closed()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

     public main_win(LOGIN s,String k ) throws SQLException {
            try {
                initComponents();
                Class.forName("com.mysql.jdbc.Driver");
                com=DriverManager.getConnection("jdbc:mysql://localhost/db2","root","root");
                st=com.createStatement();
                this.s=s;
                this.k=k;
                show_disp();
               
                 rs =  st.executeQuery("select email from login where id='"+k+"'");
                 
                 while(rs.next())
                 {
                 
                 String sts = rs.getString("email");
                 mai.setText(sts);
                 }
                  
               
               
                un.setText(k);
                 
              
         
               
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
     
    public main_win() throws SQLException {
            try {
                initComponents();
                Class.forName("com.mysql.jdbc.Driver");
                com=DriverManager.getConnection("jdbc:mysql://localhost/db2","root","root");
                st=com.createStatement();
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }
public void setl(String s)
{
    lt.setText(s);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        TIT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        un = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mai = new javax.swing.JLabel();
        lg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lt = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        del = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(97, 212, 195));
        sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidebarMouseDragged(evt);
            }
        });
        sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sidebarMouseReleased(evt);
            }
        });

        TIT.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        TIT.setForeground(new java.awt.Color(36, 47, 65));
        TIT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TIT.setText(" IWRE");

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(36, 47, 65));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Username ");

        un.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        un.setForeground(new java.awt.Color(36, 47, 65));
        un.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 47, 65));
        jLabel3.setText("Email");

        mai.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        mai.setForeground(new java.awt.Color(36, 47, 65));
        mai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lg.setBackground(new java.awt.Color(36, 47, 65));
        lg.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lg.setForeground(new java.awt.Color(255, 255, 255));
        lg.setIcon(new javax.swing.ImageIcon("C:\\Users\\IsseI\\Documents\\NetBeansProjects\\IWRE\\icons\\signout.png")); // NOI18N
        lg.setToolTipText("Logout");
        lg.setBorderPainted(false);
        lg.setContentAreaFilled(false);
        lg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 47, 65));
        jLabel5.setText("Last Tutorial :");

        lt.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lt.setForeground(new java.awt.Color(36, 47, 65));

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(mai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TIT, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lg, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                        .addComponent(un, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(TIT)
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(un, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(mai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(lg)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        parent.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 630));

        content.setBackground(new java.awt.Color(36, 47, 65));
        content.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                contentMouseDragged(evt);
            }
        });
        content.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                contentMouseReleased(evt);
            }
        });

        add.setIcon(new javax.swing.ImageIcon("C:\\Users\\IsseI\\Documents\\NetBeansProjects\\IWRE\\icons\\add.png")); // NOI18N
        add.setToolTipText("Add new tutorial or website.");
        add.setContentAreaFilled(false);
        add.setFocusPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IsseI\\Documents\\NetBeansProjects\\IWRE\\icons\\update.png")); // NOI18N
        jButton1.setToolTipText("Update existing record.");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        del.setIcon(new javax.swing.ImageIcon("C:\\Users\\IsseI\\Documents\\NetBeansProjects\\IWRE\\icons\\DEL.PNG")); // NOI18N
        del.setBorderPainted(false);
        del.setContentAreaFilled(false);
        del.setFocusPainted(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        t1.setBackground(new java.awt.Color(36, 47, 65));
        t1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Topic", "Website", "Date", "Deadline"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t1);
        if (t1.getColumnModel().getColumnCount() > 0) {
            t1.getColumnModel().getColumn(0).setResizable(false);
            t1.getColumnModel().getColumn(1).setResizable(false);
            t1.getColumnModel().getColumn(2).setResizable(false);
            t1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(del)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(del, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        parent.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 850, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void contentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentMousePressed
        // TODO add your handling code here:
             setOpacity((float)0.8);
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_contentMousePressed

    private void contentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentMouseReleased
        // TODO add your handling code here:
          setOpacity((float)1.0);
    }//GEN-LAST:event_contentMouseReleased

    private void contentMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contentMouseDragged
        // TODO add your handling code here:
           int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_contentMouseDragged

    private void sidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_sidebarMouseReleased

    private void sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx=evt.getX();
        xy=evt.getY();
    }//GEN-LAST:event_sidebarMousePressed

    private void sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);

    }//GEN-LAST:event_sidebarMouseDragged

    private void lgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgActionPerformed
        // TODO add your handling code here:
        s.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_lgActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
            try {
                // TODO add your handling code here:
                String d = un.getText();
                ADD A1 = new ADD (this,d);
                setVisible(false);
                A1.setVisible(true);
                 
            } catch (SQLException ex) {
                Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
                // TODO add your handling code here:
                String d = un.getText();
                upda u= new upda (this,d);
                setVisible(false);
                u.setVisible(true);
                 
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        try {
                // TODO add your handling code here:
                String ds = un.getText();
                del d1 = new del (this,ds);
                setVisible(false);
                d1.setVisible(true);
                  
            } catch (SQLException ex) {
                Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_delActionPerformed

  void show_disp() throws SQLException
  {
      rs= st.executeQuery("select * from w_info where id='"+k+"'");
      t1.setModel(DbUtils.resultSetToTableModel(rs));
      
      
      
  }
  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new main_win().setVisible(true);
                    
                   
                } catch (SQLException ex) {
                    Logger.getLogger(main_win.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TIT;
    private javax.swing.JButton add;
    private javax.swing.JPanel content;
    private javax.swing.JButton del;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lg;
    private javax.swing.JLabel lt;
    private javax.swing.JLabel mai;
    private javax.swing.JPanel parent;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable t1;
    private javax.swing.JLabel un;
    // End of variables declaration//GEN-END:variables
}
